### ISSUE TITLE
[FEATURE] Ability to specify which jobs are necessary

### ISSUE THREAD

**Issue by TWiStErRob** [hadialqattan/relies-on#2]
```
    steps:
      - uses: hadialqattan/relies-on@v1.0.0
        with:
          workflow: CI
          jobs: [build, deploy]
```

I'm looking to do this, because a dependent workflow might be executed as soon as the build and deploy is successful. But there could be other tasks, like test, static analysis, security tests, UI tests etc. that take longer, but not blocking the dependent workflow.
